apiVersion: apps/v1
kind: Deployment
metadata:
  name: devices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devices
  template:
    metadata:
      labels:
        app: devices
    spec:
      containers:
      - name: devices
        image: appinsightsdp.azurecr.io/msdevices:10
        env:
        - name: ServiceBus__ConnectionString
          valueFrom:
            secretKeyRef:
              name: devicessecrets # the name of the Kubernetes secret containing the data
              key: SERVICEBUSCONNECTIONSTRING # the key inside the Kubernetes secret containing the data
        - name: ServiceBus__TopicName
          value: "messagebus"
        - name: APPINSIGHTS_INSTRUMENTATIONKEY
          valueFrom:
            secretKeyRef:
              name: devicessecrets # the name of the Kubernetes secret containing the data
              key: APPINSIGHTS_INSTRUMENTATIONKEY # the key inside the Kubernetes secret containing the data
        - name: Cosmos__ConnectionString
          valueFrom:
            secretKeyRef:
              name: devicessecrets # the name of the Kubernetes secret containing the data
              key: CosmosConnectionString # the key inside the Kubernetes secret containing the data
        - name: Cosmos__DbName
          valueFrom:
            secretKeyRef:
              name: devicessecrets # the name of the Kubernetes secret containing the data
              key: CosmosDbName # the key inside the Kubernetes secret containing the data
        - name: Cosmos__DbContainerName
          valueFrom:
            secretKeyRef:
              name: devicessecrets # the name of the Kubernetes secret containing the data
              key: CosmosDbContainerName # the key inside the Kubernetes secret containing the data
        - name: Cosmos__DbPartitionKey
          valueFrom:
            secretKeyRef:
              name: devicessecrets # the name of the Kubernetes secret containing the data
              key: CosmosDbPartitionKey # the key inside the Kubernetes secret containing the data
        imagePullPolicy: Always
        ports:
        - containerPort: 80