apiVersion: apps/v1
kind: Deployment
metadata:
  name: alerts
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alerts
  template:
    metadata:
      labels:
        app: alerts
    spec:
      containers:
      - name: alerts
        image: appinsightsdp.azurecr.io/msalerts:10
        env:
        - name: ServiceBus__ConnectionString
          value: "ServiceBus__ConnectionString_Value"
        - name: ServiceBus__TopicName
          value: "messagebus"      
        imagePullPolicy: Always
        ports:
        - containerPort: 8080