name: .NET Core

on:
  push:
    branches: [ main ]
    paths:
      - './BackEnd/MicroAlerts/MicroAlerts/**'
      - '.github/workflows/MicroAlerts_CICD.yml'      
  pull_request:
    branches: [ main ]

jobs:
  Build_and_deploy_to_ACR:
    runs-on: ubuntu-latest
    env:
      workDir: ./BackEnd         
    steps:
    - uses: actions/checkout@v2    
    - name: Docker Build Alerts Microservice
      run: |
        docker build -t ${{ secrets.CONTAINER_REGISTRY }}/msalerts:${{ github.run_number }} -f ${{env.workDir}}/MicroAlerts/MicroAlerts/Dockerfile ${{env.workDir}}
    - name: ACR authentication    
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.CONTAINER_REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}  
    - name: Docker Build & Push to ACR      
      run: |
        docker push ${{ secrets.CONTAINER_REGISTRY }}/msalerts:${{ github.run_number }}    
    
  Deploy_to_App_Service:
    runs-on: ubuntu-latest
    env:      
      MSALERTS_WEBAPP_NAME: appinsightsmsalerts
    steps:
      - name: Azure authentication
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: 'Deploy to Azure Web App for Container'      
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.MSALERTS_WEBAPP_NAME }} 
          images: ${{ secrets.CONTAINER_REGISTRY }}/msalerts:${{ github.run_number }}
          slot-name: 'production' 
        
        
