name: CI_CD__Devices_Microservice

on:
  push:
    branches: [ IaC ]
    paths:      
      - '.github/workflows/Setup_PaaS.yml'
      - 'IaC/PaaS_Infra.ps1' 
      - 'IaC/AKS_Infra.ps1'
  pull_request:
    branches: [ IaC ]

jobs:
  Create_PaaS_Infra:
    runs-on: ubuntu-latest      
    steps:
    - uses: actions/checkout@v2
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_SUB}}
        enable-AzPSSession: true 
    - name: 'Run Setup PaaS powershell'
      shell: pwsh
      run: IaC/PaaS_Infra.ps1
  Create_AKS_Infra:
    needs: Create_PaaS_Infra
    env:
      SP_ID: ${{secrets.AKS_SERVICE_PRINCIPAL_ID}}    
      SP_SECRET: ${{secrets.AKS_SERVICE_PRINCIPAL_SECRET}}    
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v2
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_SUB}}
        enable-AzPSSession: true 
    - name: 'Run Setup PaaS powershell'
      shell: pwsh
      run: IaC/AKS_Infra.ps1